In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the third element
third = arr[2]          # 30
print(third)

# Get the first three elements
first_three = arr[:3]   # [10 20 30]
print(first_three)


# Replace 30 with 35
arr[2] = 35
print(arr[2])

In [7]:
import numpy as np

numbers = np.arange(1, 11)

mean = np.mean(numbers)
maximum = np.max(numbers)
minimum = np.min(numbers)

print("Array:", numbers)
print("Mean:", mean)
print("Maximum:", maximum)
print("Minimum:", minimum)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Maximum: 10
Minimum: 1


In [8]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.sum())
print(arr.sum(axis = 1))


(3, 3)
45
[ 6 15 24]


In [9]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[1][1])
print(arr[:,2])
print(arr[1,:])


5
[3 6 9]
[4 5 6]
